# Generated by Django 4.1.7 on 2023-08-28 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_alter_businessrequest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicespackageprice',
            name='period_days',
            field=models.IntegerField(default=0, verbose_name='Период в днях'),
        ),
        migrations.RemoveField(
            model_name='servicespackageprice',
            name='services_package',
        ),
        migrations.AddField(
            model_name='servicespackageprice',
            name='services_package',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='client.servicespackage', verbose_name='Пакет услуг'),
            preserve_default=False,
        ),
    ]
