# Generated by Django 4.1.7 on 2023-08-28 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_remove_servicespackageprice_count_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicespackageprice',
            name='count_period',
            field=models.IntegerField(default=0, verbose_name='Количество периодов'),
        ),
        migrations.AddField(
            model_name='servicespackageprice',
            name='period',
            field=models.ForeignKey(blank=True, default='', help_text='Установите период за сколько будет браться цена', on_delete=django.db.models.deletion.CASCADE, to='client.period', verbose_name='В'),
        ),
    ]
