# Generated by Django 4.1.7 on 2023-08-28 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_servicespackageprice_count_period_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicespackageprice',
            name='period',
            field=models.ForeignKey(blank=True, default='', help_text='Установите период за сколько будет браться цена', on_delete=django.db.models.deletion.SET_DEFAULT, to='client.period', verbose_name='В'),
        ),
    ]
