# Generated by Django 4.1.7 on 2023-08-28 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0020_alter_servicespackageprice_period_delete_periodtime'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Period',
            new_name='PeriodTime',
        ),
    ]
