# Generated by Django 4.1.7 on 2023-08-28 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0021_rename_period_periodtime'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PeriodTime',
            new_name='Period',
        ),
    ]
