# Generated by Django 4.1.7 on 2023-08-28 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_alter_client_communication'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicespackage',
            name='content',
            field=models.TextField(blank=True, default='', verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='servicespackage',
            name='price',
            field=models.FloatField(default=0, verbose_name='Стоимость'),
        ),
    ]
