# Generated by Django 4.1.7 on 2023-08-28 10:09

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_servicespackage_content_servicespackage_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicespackage',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='Текст'),
        ),
    ]
