# Generated by Django 4.1.7 on 2023-08-28 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0014_alter_servicespackageprice_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='title',
            field=models.CharField(max_length=16, unique=True, verbose_name='Титл'),
        ),
    ]
