# Generated by Django 4.1.7 on 2023-08-28 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0016_periodtime_alter_servicespackageprice_period_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessrequest',
            name='services_package_price',
            field=models.ManyToManyField(related_name='services_package_price', to='client.servicespackageprice', verbose_name='Пакет услуг'),
        ),
    ]
