# Generated by Django 4.1.7 on 2023-08-28 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0017_delete_period_and_more'),
    ]