# Generated by Django 4.1.7 on 2023-08-28 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0022_rename_periodtime_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessrequest',
            name='services_package_price',
            field=models.ManyToManyField(related_name='package', to='client.servicespackageprice', verbose_name='Пакет услуг'),
        ),
    ]
