# Generated by Django 4.1.7 on 2023-08-23 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_article_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='number_articles',
        ),
        migrations.AlterField(
            model_name='writer',
            name='avatar_image',
            field=models.ImageField(upload_to='writer/avatar/', verbose_name='Аватар'),
        ),
    ]
