# Generated by Django 4.1.7 on 2023-08-23 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_article_number_articles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writer',
            name='avatar_image',
            field=models.ImageField(blank=True, null=True, upload_to='writer/avatar/', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='writer',
            name='lastname',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='writer',
            name='pastname',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Отчество'),
        ),
    ]
