# Generated by Django 4.1.7 on 2023-08-26 21:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_article_time_at_alter_writer_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='time_at',
            field=models.TimeField(default=datetime.datetime(2023, 8, 27, 0, 49, 18, 527707), verbose_name='Время создания'),
        ),
    ]
