# Generated by Django 4.1.7 on 2023-08-28 23:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_alter_article_time_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='time_at',
            field=models.TimeField(default=datetime.datetime(2023, 8, 29, 2, 36, 0, 66312), verbose_name='Время создания'),
        ),
    ]
