# Generated by Django 4.1.7 on 2023-09-27 22:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_alter_article_time_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='time_at',
            field=models.TimeField(default=datetime.datetime(2023, 9, 28, 1, 19, 35, 513276), verbose_name='Время создания'),
        ),
    ]
