# Generated by Django 4.1.7 on 2023-11-04 21:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_alter_article_time_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brandsupport',
            options={'verbose_name': 'Бренд в России', 'verbose_name_plural': 'Бренды в России'},
        ),
        migrations.AddField(
            model_name='article',
            name='video',
            field=models.CharField(blank=True, default=None, max_length=256, null=True, verbose_name='Ссылка на видео'),
        ),
        migrations.AlterField(
            model_name='article',
            name='time_at',
            field=models.TimeField(default=datetime.datetime(2023, 11, 5, 0, 34, 51, 488603), verbose_name='Время создания'),
        ),
    ]
