# Generated by Django 4.1.7 on 2023-11-05 10:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_alter_brandsupport_options_article_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandsupport',
            name='number',
            field=models.IntegerField(default=-1, verbose_name='Порядковый номер'),
        ),
        migrations.AlterField(
            model_name='article',
            name='time_at',
            field=models.TimeField(default=datetime.datetime(2023, 11, 5, 13, 18, 31, 102976), verbose_name='Время создания'),
        ),
    ]
