# Generated by Django 4.1.7 on 2023-11-05 10:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_alter_article_time_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='time_at',
            field=models.TimeField(default=datetime.datetime(2023, 11, 5, 13, 32, 30, 889864), verbose_name='Время создания'),
        ),
    ]
