# Generated by Django 4.1.7 on 2023-11-05 14:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_alter_article_time_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='time_at',
            field=models.TimeField(default=datetime.datetime(2023, 11, 5, 17, 40, 31, 773940), verbose_name='Время создания'),
        ),
    ]
