# Generated by Django 4.1.7 on 2023-08-28 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0005_remove_page_submenu_page_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='files',
            field=models.ManyToManyField(default=None, null=True, related_name='files', to='docs.file', verbose_name='Файлы'),
        ),
    ]
