# Generated by Django 4.1.7 on 2023-08-28 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0007_alter_page_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='link',
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='docs/', verbose_name='Файл'),
        ),
    ]
