# Generated by Django 4.1.7 on 2023-09-27 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0009_alter_file_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='isVisible',
            field=models.BooleanField(default=False, verbose_name='Отображать меню'),
        ),
        migrations.AddField(
            model_name='menu',
            name='number',
            field=models.IntegerField(default=1, verbose_name='Порядковый номер'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='isVisible',
            field=models.BooleanField(default=False, verbose_name='Отображать страницу'),
        ),
    ]
