# Generated by Django 4.1.7 on 2023-11-05 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0010_menu_isvisible_menu_number_page_isvisible'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='number',
            field=models.IntegerField(default=-1, verbose_name='Порядковый номер'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='number',
            field=models.IntegerField(default=-1, verbose_name='Порядковый номер'),
        ),
    ]
