# Generated by Django 4.1.7 on 2023-11-05 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0011_page_number_alter_menu_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='number',
            field=models.IntegerField(default=999, verbose_name='Порядковый номер'),
        ),
    ]
