# Generated by Django 4.1.7 on 2023-11-05 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0012_alter_page_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='number',
            field=models.IntegerField(default=999, verbose_name='Порядковый номер'),
        ),
    ]
