# Generated by Django 4.1.7 on 2023-08-28 18:39

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=64, unique=True, verbose_name='Ссылка на файл')),
                ('file', models.FilePathField(path='docs/', verbose_name='Файл')),
                ('title', models.CharField(max_length=128, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=64, unique=True, verbose_name='Путь')),
                ('title', models.CharField(max_length=128, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Меню',
                'verbose_name_plural': 'Меню',
            },
        ),
        migrations.CreateModel(
            name='SubMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=64, unique=True, verbose_name='Путь')),
                ('title', models.CharField(max_length=128, unique=True, verbose_name='Название')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docs.menu', verbose_name='Меню')),
            ],
            options={
                'verbose_name': 'Подменю',
                'verbose_name_plural': 'Подменю',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=64, unique=True, verbose_name='Путь')),
                ('title', models.CharField(max_length=128, unique=True, verbose_name='Название')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Содержимое')),
                ('files', models.ManyToManyField(related_name='files', to='docs.file', verbose_name='Файлы')),
                ('submenu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docs.submenu', verbose_name='Подменю')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
            },
        ),
    ]
