# Generated by Django 4.1.7 on 2023-08-28 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0004_alter_page_submenu_delete_submenu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='submenu',
        ),
        migrations.AddField(
            model_name='page',
            name='menu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='docs.menu', verbose_name='Меню'),
            preserve_default=False,
        ),
    ]
