# Generated by Django 4.1.7 on 2023-08-28 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0006_alter_page_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='files',
            field=models.ManyToManyField(blank=True, default='', related_name='files', to='docs.file', verbose_name='Файлы'),
        ),
    ]
