# Generated by Django 4.1.7 on 2023-08-23 15:17

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrandPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=128, unique=True, verbose_name='Путь')),
                ('title', models.CharField(max_length=128, unique=True, verbose_name='Название')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Описание')),
                ('link', models.CharField(max_length=128, verbose_name='Ссылка на страницу бренда')),
                ('logo_image', models.ImageField(upload_to='brand_partner/logo/', verbose_name='Логотип')),
            ],
            options={
                'verbose_name': 'Партнёр бренда',
                'verbose_name_plural': 'Партнёры бренда',
            },
        ),
        migrations.CreateModel(
            name='BrandSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=128, unique=True, verbose_name='Путь')),
                ('title', models.CharField(max_length=128, unique=True, verbose_name='Название')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Описание')),
                ('link', models.CharField(max_length=128, verbose_name='Ссылка на страницу бренда')),
                ('logo_image', models.ImageField(upload_to='brand_support/logo/', verbose_name='Логотип')),
            ],
            options={
                'verbose_name': 'Поддержка бренда',
                'verbose_name_plural': 'Поддержка бренда',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=128, unique=True, verbose_name='Путь')),
                ('title', models.CharField(max_length=128, unique=True, verbose_name='Название')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Тэг',
                'verbose_name_plural': 'Тэги',
            },
        ),
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=128, unique=True, verbose_name='Путь')),
                ('firstname', models.CharField(max_length=128, verbose_name='Имя')),
                ('lastname', models.CharField(max_length=128, verbose_name='Фамилия')),
                ('pastname', models.CharField(max_length=128, verbose_name='Отчество')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Описание')),
                ('avatar_image', models.ImageField(upload_to='writer/avatar/', verbose_name='Логотип')),
                ('number_articles', models.IntegerField(default=0, verbose_name='Количество статей')),
            ],
            options={
                'verbose_name': 'Писатель',
                'verbose_name_plural': 'Писатели',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=128, unique=True, verbose_name='Путь')),
                ('title', models.CharField(max_length=128, unique=True, verbose_name='Название')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Описание')),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='article/preview/', verbose_name='Обложка')),
                ('number_articles', models.IntegerField(default=0, verbose_name='Количество статей')),
                ('date_creation', models.DateField(default=datetime.date.today, verbose_name='Дата создания')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Контент')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.brandpartner', verbose_name='Бренд')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.writer', verbose_name='Писатель')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
    ]
