# Generated by Django 4.1.7 on 2023-08-24 22:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_tag_options_alter_article_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='date_creation',
            new_name='date_at',
        ),
        migrations.AddField(
            model_name='article',
            name='time_at',
            field=models.TimeField(default=datetime.datetime(2023, 8, 25, 1, 16, 38, 422299), verbose_name='Время создания'),
        ),
    ]
