# Generated by Django 4.1.7 on 2023-08-25 00:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_article_time_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='time_at',
            field=models.TimeField(default=datetime.datetime(2023, 8, 25, 3, 0, 35, 712398), verbose_name='Время создания'),
        ),
    ]
