# Generated by Django 4.1.7 on 2023-08-26 18:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_article_time_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='writer',
            name='rank',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='article',
            name='time_at',
            field=models.TimeField(default=datetime.datetime(2023, 8, 26, 21, 35, 22, 472076), verbose_name='Время создания'),
        ),
    ]
