# Generated by Django 4.1.7 on 2023-08-26 20:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_writer_rank_alter_article_time_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='time_at',
            field=models.TimeField(default=datetime.datetime(2023, 8, 26, 23, 25, 29, 442262), verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='writer',
            name='rank',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='Должность'),
        ),
    ]
