# Generated by Django 4.1.7 on 2023-08-26 22:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_article_time_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='time_at',
            field=models.TimeField(default=datetime.datetime(2023, 8, 27, 1, 12, 59, 708608), verbose_name='Время создания'),
        ),
    ]
