# Generated by Django 4.1.7 on 2023-08-27 11:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_article_time_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='time_at',
            field=models.TimeField(default=datetime.datetime(2023, 8, 27, 14, 45, 37, 511971), verbose_name='Время создания'),
        ),
    ]
