# Generated by Django 4.1.7 on 2023-08-28 18:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_alter_article_time_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='time_at',
            field=models.TimeField(default=datetime.datetime(2023, 8, 28, 21, 39, 50, 633786), verbose_name='Время создания'),
        ),
    ]
