# Generated by Django 4.1.7 on 2023-08-28 20:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_alter_article_time_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='time_at',
            field=models.TimeField(default=datetime.datetime(2023, 8, 28, 23, 55, 2, 907496), verbose_name='Время создания'),
        ),
    ]
