# Generated by Django 4.1.7 on 2023-09-30 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(max_length=128, verbose_name='Страница')),
                ('calling_error', models.TextField(verbose_name='Вызов ошибки')),
                ('description', models.TextField(verbose_name='Описание ошибки')),
            ],
            options={
                'verbose_name': 'Ошибка на сайте',
                'verbose_name_plural': 'Ошибки на сайте',
            },
        ),
    ]
