# Generated by Django 4.1.7 on 2023-11-05 14:33

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Титульник')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Содержание письма')),
            ],
            options={
                'verbose_name': 'Тело письма',
                'verbose_name_plural': 'Тела писем',
            },
        ),
    ]
