# Generated by Django 4.1.7 on 2023-11-05 14:40

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0002_mailbody'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailFooter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Не будет отображаться в письме', max_length=128, verbose_name='Название')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Содержание письма')),
            ],
            options={
                'verbose_name': 'Подвал письма',
                'verbose_name_plural': 'Подвал писем',
            },
        ),
        migrations.AddField(
            model_name='mailbody',
            name='footer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bugs.mailfooter', verbose_name='Подвал письма'),
        ),
    ]
